version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  test:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
